### ISSUE TITLE
Wrong when running C60 test:"Error in reading from socket"

### ISSUE THREAD

**Issue by jsboer** [thunder-dft/thunder-fireball#28]
Hi, I have cloned thunder-fireball and thunder-master, and use following command to make fireball-ase.x
```
make fireball-ase.x F90=ifort CC=icc MKLROOT=/public/software/compiler/intel/2021.3.0/mkl
```
the OPTIONS in include is 
```
SHELL = /bin/bash
COMPILER = ifort
LINALG = MKL
MODE = OPT
#MODE = DEBUG
OPENMP = FALSE
MPI = FALSE
MACHINE = HKQAI
THEORY = HORSFIELD
SCF = DOGS
DIAGONALIZATION = GAMMAD
XC = BLYP
```

Then I run the C60 test but meet error, following is the output of terminal:
```
Error in reading from socket
 ENDED 
112.2476815097034
```
The F_data I used is  
```
Fdata-Horsfield-0.15-3SN.Hs3.75.Cs4.00p4.45.Os3.35p3.80-3SNP.Fes5.30p5.30d4.80
```
The python file I used is 
```
from thunder_ase.fireball import Fireball
from ase.build import molecule
import timeit
from ase import units
# Socket Communication
from ase.calculators.socketio import SocketIOCalculator
# ase MD modules
from ase.md.verlet import VelocityVerlet as NVE


def run_with_socket():
    # Construct Structure
    atoms = molecule('C60')

    # set Fdata dir
    Fdata_path = 'Fdata'

    # Sockets
    unixsocket = 'thunder-ase'

    max_step = 10
    kwargs = {
              'ipi': 1,
              'nstepf':max_step+1,  # max step
              'inet': 0,
              'host': unixsocket,
              'scf_tolerance_set':1E-8,
              }
    fireball = Fireball(command='./fireball-ase.x', Fdata_path=Fdata_path, **kwargs)
    fireball.prefix = ''
    dyn = NVE(atoms, trajectory='md.traj', logfile='md.log', timestep=0.5 * units.fs)

    with SocketIOCalculator(fireball, log=None, unixsocket=unixsocket) as calc:
        atoms.calc = calc
        dyn.run(max_step)

print(timeit.timeit(run_with_socket, number=1))

```

The input and output file is in attachment, what could cause this error?  Thank you!

[001inp.txt](https://github.com/thunder-dft/thunder-fireball/files/14126980/001inp.txt)
[001log.txt](https://github.com/thunder-dft/thunder-fireball/files/14126981/001log.txt)
[001xyz.txt](https://github.com/thunder-dft/thunder-fireball/files/14126982/001xyz.txt)
[outputlog.txt](https://github.com/thunder-dft/thunder-fireball/files/14126983/outputlog.txt)

**Comment by renpj** [comment]
This is not a real error. The program has finished. You can check the md.log and the trajectory file. 
The error message is due to the fireball-ase.x didn't send a proper signal to socket when the loop finished. We will fix this in the future.
